[project]
name = "python-ai-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "deepagents>=0.3.6",
    "langchain>=1.2.6",
    "langchain-community>=0.4.1",
    "langgraph>=1.0.6",
]
